#!/bin/bash

GIT_HOME=`git rev-parse --show-toplevel`

# Find modified files
DIFF_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".js$"))
if [[ "$DIFF_FILES" = "" ]]; then
  # No js files to be checked.
  exit 0
fi

# Jump to git root dir
pushd ${GIT_HOME}

# Is eslint installed?
which eslint > /dev/null
if [ $? -ne 0 ];
then
  echo -e "\033[41;37mPlease install ESLint:\033[0m"
  echo "yarn global add eslint eslint-config-airbnb-base eslint-plugin-import"
  exit 1
fi

# Run ESLint
eslint -c .eslintrc.yaml "${DIFF_FILES[@]}"
ESLINT_EXIT="$?"

# Back to original dir
popd

# ESLint result
if [[ "${ESLINT_EXIT}" == 0 ]];
then
  echo -e "\033[31mCOMMIT SUCCEEDED\033[0m"
else
  echo -e "\033[41;37mCOMMIT NOT ALLOWED:\033[0m Please fix ESLint errors."
  exit 1
fi

exit $?
